[package]
name = "telegram-bot-rust"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.151", features = ["derive"] }
